<?php

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\ConfirmablePasswordController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\EmailVerificationPromptController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\Auth\VerifyEmailController;
use Illuminate\Support\Facades\Route;

// Routes for signed-out visitors only. The "guest" middleware bounces anyone
// already logged in away from these pages (e.g. back to the dashboard).
Route::middleware('guest')->group(function () {
    // Registration: GET renders the sign-up form, POST creates the user.
    Route::get('register', [RegisteredUserController::class, 'create'])
        ->name('register');

    Route::post('register', [RegisteredUserController::class, 'store']);

    // Login: GET renders the login form (the view commented earlier), POST
    // verifies credentials and starts the authenticated session.
    Route::get('login', [AuthenticatedSessionController::class, 'create'])
        ->name('login');

    Route::post('login', [AuthenticatedSessionController::class, 'store']);

    // Password reset, step 1: request the email that carries the reset link.
    Route::get('forgot-password', [PasswordResetLinkController::class, 'create'])
        ->name('password.request');

    Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])
        ->name('password.email');

    // Password reset, step 2: {token} is the one-time token from the emailed
    // link. It is validated before the new password is saved.
    Route::get('reset-password/{token}', [NewPasswordController::class, 'create'])
        ->name('password.reset');

    Route::post('reset-password', [NewPasswordController::class, 'store'])
        ->name('password.store');
});

// Routes for logged-in users only ("auth" redirects guests to the login page).
Route::middleware('auth')->group(function () {
    // Shown when a verified email is required but the user has not confirmed yet.
    Route::get('verify-email', EmailVerificationPromptController::class)
        ->name('verification.notice');

    // Handles the link clicked in the verification email. "signed" proves the
    // URL was generated by the app (not tampered with); "throttle:6,1" limits
    // the route to 6 attempts per minute to slow down guessing.
    Route::get('verify-email/{id}/{hash}', VerifyEmailController::class)
        ->middleware(['signed', 'throttle:6,1'])
        ->name('verification.verify');

    // Resends the verification email, rate limited for the same reason.
    Route::post('email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
        ->middleware('throttle:6,1')
        ->name('verification.send');

    // "Confirm password" gate in front of sensitive actions: asks the user to
    // re-enter their current password even though they are already logged in.
    Route::get('confirm-password', [ConfirmablePasswordController::class, 'show'])
        ->name('password.confirm');

    Route::post('confirm-password', [ConfirmablePasswordController::class, 'store']);

    // Change the password from within the account settings (PUT = full update
    // of the password resource).
    Route::put('password', [PasswordController::class, 'update'])->name('password.update');

    // Ends the session and invalidates the remember cookie.
    Route::post('logout', [AuthenticatedSessionController::class, 'destroy'])
        ->name('logout');
});
